### PR TITLE
Add minimap support (ST3 only)

### PR DESCRIPTION
**Pull request by bbrks**
I've added support for showing gutter marks in the minimap (#55), but it only works on ST3.
Unsure if you want to merge or not because of this, however it does safely disable in ST2.

Here's a screenshot showing ST3 and ST2 respectively.

screen shot 2015-08-05 at 21 07 49

Here's a non-retina screenshot showing a much bigger file. Makes it a lot easier to spot diffs.

screen shot 2015-08-06 at 10 40 37

### CODE REVIEW

**Comment by johnmela** [comment]
Any chance of this getting merged?

**Comment by sigod** [comment]
Interesting. I have somehow missed this PR.

@bbrks Can you resolve conflicts?

**Comment by bbrks** [comment]
Sure, I'll have another look.

**Comment by jisaacks** [comment]
I completely missed this as well. Thanks for bringing back up.

**Comment by jisaacks** [comment]
I would love to get this feature in. I have a few questions on top of the rebasing.

@bbrks what is the `+1` for [here](https://github.com/jisaacks/GitGutter/pull/243/files#diff-33236be00bb121dbc530dbcff9d359aaR85)? Also is there anyway to break [this](https://github.com/jisaacks/GitGutter/pull/243/files#diff-33236be00bb121dbc530dbcff9d359aaR130) up into a couple lines to make more readable?

**Comment by bbrks** [comment]
@jisaacks The +1 is to give the region a width of 1 char to display on the minimap. The minimap cannot display anything of zero width.

I will be able to break the one liner flag up, I should have it done by the end of the day. I'd love to get this merged! Having diff marks in the minimap has been invaluable.

**Comment by bbrks** [comment]
Should be good to go! :+1:

**Comment by jisaacks** [comment]
@bbrks thanks, I pulled your branch down locally to play with for a bit.

**Comment by bbrks** [comment]
Thanks for the merge!

**Pull request merged**
