### PR TITLE
Move Documentation to GitHub Pages

### PR DESCRIPTION
**Pull request by deathaxe**
The README.md has grown over time and is therefore hard to read.

This PR therefore splits it into logical pieces and uses `mkdocs` to create the required html for GitHub Pages. The documentation will be available via https://jisaacks.github.io/GitGutter.

@jisaacks: I've already created the required _gh-pages_ branch with the built web pages. If we decide to use g-pages for docs, could you please setup git hub pages it in the repository settings?

### CODE REVIEW

**Comment by jisaacks** [comment]
@deathaxe when I go there, it says it is already set up.
screen shot 2018-06-19 at 11 21 09 am

**Comment by deathaxe** [comment]
Maybe the publishing needs to be triggered somehow? 

To check that, I forked the repo but the pages were not published via https://deathaxe.github.io/GitGutter as well. After changing the setting to "master branch" hitting save and revert it back to "gh-pages" branch the pages got published after some seconds.

The state about publishing is even visible at the page now.

screenshot

**Comment by jisaacks** [comment]
@deathaxe that worked thanks. It is live now: http://jisaacks.github.io/GitGutter/

**Comment by deathaxe** [comment]
OK.

**Pull request merged**
