### PR TITLE
Async git invocations

### PR DESCRIPTION
**Pull request by entombedvirus**
Disclaimer: This pull req contains extensive changes to GitGutter and I can totally understand if you would rather not accept it.

That said, I use GitGutter regularly on large-ish git repos (~8GB) and I've grown so accustomed to it that  having had to turn GitGutter off due to noticeable delays while typing made me miss it sorely. I tried many combinations of non-blocking, live-mode & debounce_delay and still could not achieve the kind of user experience I wanted: for GitGutter not to introduce _any_ typing lag regardless of size of the git repo.

Some initial experimentation led to the conclusion that calling subprocess.Popen(...) in a separate thread using sublime.set_timeout_async gets rid of the typing lag. But that meant changing the codebase from blocking calls to some kind of async callback style code. I chose to use a poor man's implementation of Promise API for async callbacks.

These are the main highlights of this pull request:
1. git is invoked on a separate thread as to not introduce any delay while typing
2. the compare target is now per git dir. Previously, if you were comparing against tag/0.1.1 in one git repo, GitGutter would diff against that tag on every single window regardless of whether they were separate git projects. Now it will only diff against tag/0.1.1 for projects that share the same .git dir
3. Fixed "Compare against origin" so that it's functional

**I have only tested this on Sublime Text 3 running on OS X as that's the only platform I currently have access to.**

### CODE REVIEW

**Comment by entombedvirus** [comment]
Oh forgot to mention another highlight:

untracked and ignored file detection has been made lazy so as to minimize needless git invocations

**Comment by sigod** [comment]
Wow, you literally rewrote whole GitGutter.

I'll try it at day to day work.

**Comment by entombedvirus** [comment]
@sigod did you get a chance to try it out? If so, what OS and Sublime version are you on?

**Comment by sigod** [comment]
Yes, I currently use it at work.

Windows 7, x64. Latest Sublime Text 3.

**Comment by jisaacks** [comment]
@entombedvirus This is a big PR. I appreciate the work you put into this. However, I want to make sure to review all of the code carefully since this changes so much. I may not be able to get to this for a month or two.

**Comment by entombedvirus** [comment]
Yep, makes sense. Let me know if I can help by answering questions etc. :)

**Comment by sigod** [comment]
Looks like async version of GitGutter causes Package Manager to hang.

screenshot 2015-08-03 23 02 58

Also, Package Manager never loads "install package" interface with GitGutter installed. Even if GitGutter disabled.

Not sure what is going on.

**Comment by jisaacks** [comment]
@sigod thanks so much for testing this out and figuring out it's issues. @entombedvirus is this something you are interested in resolving?

**Comment by ldionne** [comment]
Is there any interest in this PR anymore? I am amongst those suffering from GitGutter lagging when using Sublime over SSHFS, and the only solution right now is to turn off GitGutter altogether :-(. @entombedvirus Would it be possible to scale down the changes in this PR so that the core functionality of async Git invocations is still retained, while making the review and integration easier for @jisaacks ?

**Comment by rasky** [comment]
@entombedvirus since the owner of this package is not merging this PR which is a showstopper for medium-sized projects, would it possible for you to repackage and publish your version independently? I would love to be able to easily install it though the package manager.

**Comment by rchl** [comment]
I think it's unacceptable that such issue wasn't yet fixed, even after the pull request was ready more than a year ago. Slowing down editing experience not only is bad for the user but also for the image of the editor itself. People will not realize what's the reason for the freezes and blame the editor.

I'm working with local but big repo and switching between files and immediately trying to move the cursor freezes for a split second, which is already annoying enough for me.

I'm not sure if @entombedvirus is still around but I've taken his changes and rebased on latest master. Also rewritten Promise implementation a bit and fixed some style issues. Unfortunately I had to squash all the commits as it would be too difficult to rebase with original commit structure. I'm not sure if there is any interest in such commit as it would be hard to review... Splitting it in smaller chunks would be rather time consuming and not sure how feasible as changes kinda depend on each other.

I think @entombedvirus changes not only resolve the problem but also make the design of the code much nicer, with less globals, more code sharing and using TextCommands where it's more appropriate to use those then WindowCommands.

> Looks like async version of GitGutter causes Package Manager to hang.

I think it unrelated issues. More related to having a git repo checked out in the packages directory than to the changes itself.

**Comment by rasky** [comment]
@sigod would it be possible to get this reviewed and hopefully merged please? It's a showstoppers for many people. I'm forced to uninstall GitGutter most of the time because of this.

**Comment by rchl** [comment]
BTW. It would probably be fairly easy to reorganize the commit into two steps - big refactoring to remove globals and ViewCollection and then add async invocations on top of that. The first commit would still be big and fairly difficult to review though.

**Comment by ldionne** [comment]
@rchl Thank you so much for doing this. @jisaacks Can we please merge this in?

**Comment by ldionne** [comment]
@rchl Unless I'm mistaken, you should publish your own PR with the rebased changes, right?

**Comment by rchl** [comment]
Sure, I could, but these are mostly @entombedvirus' changes so I don't necessarily want to "steal" them from him. :)

And besides, if original pull request was not merged then why should I think that same changes will be merged now? :)

**Comment by entombedvirus** [comment]
hey @rchl, thanks for picking up where I left off :)

Since I am no longer an active user of Sublime, I don't think I can give this PR the proper attention it deserves. Consider this a go-ahead from me to use the code in this PR however you see fit. If it's easier, you don't have to keep the git history intact: flatten away.

If you're up to it, IMO you should submit your fork as a separate entry in Package Control so that other users can just install your fork.

**Comment by jisaacks** [comment]
> I think it's unacceptable that such issue wasn't yet fixed

@rchl Welcome to free software. Getting this issue which only effects a very small amount of user's isn't everyone's highest priority. The PR was reviewed, changes were requested, they never happened. Not my or anyone else's responsibility to spend time working on issues that don't effect them.

>  @jisaacks Can we please merge this in?

@ldionne if a fix is made, code is clean, and there are no regressions, I would be happy to merge. But this is not a feature I am going to work on myself. However I am very busy these days, having a full time job, a family and working on a book, doesn't leave me with ample amounts if time to dedicate to what I consider non critical issues. So If no one else can review it than it will have to wait until I can find the time. However if either @sigod or @r-stein sign off then it would be good enough for me (as long as a mac test is done, I think they are both windows guys.) Or if anyone else wants to volunteer to make sure this is a good merge and take responsibility for merging I would gladly add them as a collaborator.

**Comment by ldionne** [comment]
OK, so let's close this PR and let @rchl reopen one with the latest rebased code. Then we can get a code review and testing started and stop pulling each other's hair. I'm willing to test the patch on Mac on my SSHFS mount (where latencies were a problem) if someone can direct me how to use a locally-built package with Sublime.

**Comment by rchl** [comment]
I'll do my best to get a pull request ready, separating refactoring from async fix.

I have both Mac and Windows so can try both but if you will want to try my code, you just need to uninstall original GitGutter package and then clone the branch of the pull request into Sublime's Packages directory (on Mac that would probably be `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/`).

**Comment by jisaacks** [comment]
Also is anyone would test on ST2 that would also be great, there are still a fair bit of users on ST2. Instructions on manually installing from git are in the read me :)

**Comment by jisaacks** [comment]
Also I'll close this PR once a new PR is submitted.

**Comment by r-stein** [comment]
May be worth to say, that the Package Control issue is not related to the code, but to git Packages. If you use have your packages as a git directory it automatically tries to pull from the remote. However if the remote is not existings this error pops up. I assume, that the same thing happens when the origin does not have the branch.
Just open the Package Control settings `Preferences >> Package Settings >> Package Control` and and add `"ignore_vcs_packages": true,` to avoid this.

**Comment by rchl** [comment]
Removal of ViewCollection was merged already and async invocations are to be merged soon (#321) so closing this now. Special thanks to @entombedvirus for the initial work. :)

There are still one or two minor fixes that can be picked from here. Namely:

>  the compare target is now per git dir.

and

> untracked and ignored file detection has been made lazy so as to minimize needless git invocations

I will probably pick on those later.

**Pull request closed without merging**
